[package]
name = "des_system"
version = "0.1.0"
authors = ["Cody Lewis <luxdotsugi@gmail.com>","Jay Rovacsek <elevennn@protonmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
